name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.
  
  - type: dropdown
    id: issue-type
    attributes:
      label: Request Type
      description: What type of request is this?
      options:
        - New Feature
        - Enhancement
        - New API/Provider Support
      default: 0
    validations:
      required: true
  
  - type: dropdown
    id: homey-device
    attributes:
      label: Type of Homey Device
      description: Which Homey device are you using?
      options:
        - Homey Cloud
        - Homey Pro (2023)
        - Homey Pro (Early 2019)
        - Homey Bridge
        - Not device-specific
      default: 4
    validations:
      required: true
  
  - type: input
    id: app-version
    attributes:
      label: Current App Version
      description: What version of the Trashcan Reminder app are you using?
      placeholder: "e.g., 5.3.1"
    validations:
      required: true
  
  - type: input
    id: provider
    attributes:
      label: Provider/Municipality (if applicable)
      description: If this is a request for a new provider, which one?
      placeholder: "e.g., New municipality waste collection service"
    validations:
      required: false
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature you want
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe why this feature would be useful
      placeholder: Explain the problem this feature would solve
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request
    validations:
      required: false
